ci(ci.yml): streamline secret checks in CI jobs
Removed the separate check for environment variables from the 'check-envvars' job and integrated it into the 'build' job. This change simplifies the CI pipeline by reducing the number of jobs while ensuring that required secrets are still validated during the build process.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,19 +17,6 @@ env:
   MAVEN_CLI_OPTS: "-B -V -ntp --fail-at-end -T 1C"
 
 jobs:
-  check-envvars:
-    name: Check Environment Variables
-    runs-on: ubuntu-latest
-    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/dev'
-    steps:
-      - name: Check required secrets
-        run: |
-          if [[ -z "${{ secrets.SONAR_HOST_URL }}" ]] \
-          || [[ -z "${{ secrets.SONAR_TOKEN }}" ]]; then
-            echo "Missing required SonarQube secrets"
-            exit 1
-          fi
-
   build:
     name: Build
     runs-on: ubuntu-latest
@@ -201,9 +188,17 @@ jobs:
     runs-on: ubuntu-latest
     container:
       image: maven:3.9.9-eclipse-temurin-21-alpine
-    needs: [check-envvars, build, test, testIHM]
+    needs: [build, test, testIHM]
     if: github.event_name == 'pull_request' || github.ref == 'refs/heads/dev'
     steps:
+      - name: Check required secrets
+        run: |
+          if [[ -z "${{ secrets.SONAR_HOST_URL }}" ]] \
+          || [[ -z "${{ secrets.SONAR_TOKEN }}" ]]; then
+            echo "Missing required SonarQube secrets"
+            exit 1
+          fi
+
       - name: Install Git
         run: apk add --no-cache git
 
